### ISSUE TITLE
Failed to Update Arc

### ISSUE THREAD

**Issue by creative-tutorials** [devz3ro/Arc-Windows-10#14]
When I try to run the `arcwin10-1.2.2.bat` file as Admin I get this error, Why did it say reinstallation of the file was blocked tho

![image](https://github.com/devz3ro/Arc-Windows-10/assets/68476321/1eaaadb8-6b6f-4f8a-a948-7798767875b9)

**Comment by devz3ro** [comment]
This is because you used the first version of the script that I made which used a different method to install (unpack + developer mode). The new version doesn't require developer mode to be enabled, and is installed in the normal windows apps location, but it can't co-exist with the unpackaged version. You will need to completely uninstall / delete your existing installation (windows settings -> apps -> uninstall arc) before you will be able to use the new one.

Note 1: If you are using v1.0 of this script, you will need to uninstall and delete that version before you can use v1.2.2. If you have used v1.1 or v1.2.X you can use v1.2.2 without any changes.
